# DISA SRG:       SRG-NET-000362-RTR-000110
# Rule ID:        SV-221079r1055901_rule
# Severity:       medium
# Identifiers:    SV-110977, V-101873, CCI-002385, CCI-004866, CCI-001097

# The Cisco switch must be configured to protect against or limit the effects of denial-of-service (DoS) attacks by employing control plane protection.

# !! TO-DO !!
# Configure the required ACLs (as per STIG remediation)
# Create class-maps for traffic classes
# Build the policy-map with policing rates
# Apply the policy to the control-plane

- name: "[SV-221079r1055901_rule Step 1] Configure CoPP ACLs"
  cisco.nxos.nxos_config:
    lines: "{{ item }}"
  loop: >-
    {{
      copp_acl_critical | map('regex_replace', '^', 'ip access-list CoPP_CRITICAL\n ') | list +
      copp_acl_important | map('regex_replace', '^', 'ip access-list CoPP_IMPORTANT\n ') | list +
      copp_acl_normal | map('regex_replace', '^', 'ip access-list CoPP_NORMAL\n ') | list +
      copp_acl_undesirable | map('regex_replace', '^', 'ip access-list CoPP_UNDESIRABLE\n ') | list +
      copp_acl_default | map('regex_replace', '^', 'ip access-list CoPP_DEFAULT\n ') | list
    }}

- name: "[SV-221079r1055901_rule Step 2] Configure class-maps"
  cisco.nxos.nxos_config:
    lines:
      - class-map match-{{ item.type | default('all') }} {{ item.name }}
      - match access-group name {{ item.name }}
    with_items:
      - { name: 'CoPP_CRITICAL', type: 'all' }
      - { name: 'CoPP_IMPORTANT', type: 'any' }
      - { name: 'CoPP_NORMAL', type: 'all' }
      - { name: 'CoPP_UNDESIRABLE', type: 'any' }
      - { name: 'CoPP_DEFAULT', type: 'all' }

- name: "[SV-221079r1055901_rule Step 3] Build CoPP policy-map"
  cisco.nxos.nxos_config:
    lines: >-
      {{
        copp_policy_map | dict2items | map('regex_replace',
          '^(.*)$',
          'class \1\n police {{ copp_policy_map["\1"].rate }} {{ copp_policy_map["\1"].burst }}\n conform-action {{ copp_policy_map["\1"].conform }}\n exceed-action {{ copp_policy_map["\1"].exceed }}'
        ) | list
      }}
    parents: policy-map CONTROL_PLANE_POLICY

- name: "[SV-221079r1055901_rule Step 4] Apply policy-map to control plane"
  cisco.nxos.nxos_config:
    lines:
      - service-policy input CONTROL_PLANE_POLICY
    parents: control-plane
