# DISA SRG:       SRG-NET-000364-RTR-000111
# Severity:       low
# Rule ID:        SV-221096r999705_rule
# Identifiers:    SV-111011, V-101907, CCI-002403

# version 7. of NX-OS doesn't support `no lldp`

# The Cisco perimeter switch must be configured to have Link Layer Discovery Protocol (LLDP) disabled on all external interfaces.
- name: >
   [SV-221096r999705_rule Step 1 of 3] Check if LLDP is a supported feature
  cisco.nxos.nxos_command:
    commands: "show feature"
  register: lldp_features

- name: >
   [SV-221096r999705_rule Step 2 of 3] Determine if LLDP feature is supported/ enabled
  set_fact:
    lldp_feature_supported: >-
      {{
        lldp_features.stdout[0]
        | regex_search('^\\s*lldp\\s+(enabled|disabled)', ignorecase=True) is not none
      }}

- name: >
    [SV-221096r999705_rule Step 3a of 3] Disable LLDP transmit on all external interfaces
  cisco.nxos.nxos_config:
    lines:
      - no lldp transmit
    parents: "interface {{ item }}"
  loop: "{{ external_interfaces }}"
  when: lldp_feature_supported

- name: >
    [SV-221096r999705_rule Step 3b of 3] LLDP not supported so skip for compliance awareness
  debug:
    msg: >
      [!] LLDP feature not supported or not present on this platform.
      Skipping SRG-NET-000364-RTR-000111 (Disable LLDP on external interfaces).
  when: not lldp_feature_supported